"""
Keymap Visualizer – Export functions
"""

import bpy
import os
from . import state


def _kmi_to_properties_dict(kmi):
    """Extract serializable operator properties from a KMI."""
    props = {}
    try:
        if kmi.properties is not None:
            for prop_name in kmi.properties.bl_rna.properties.keys():
                if prop_name == 'rna_type':
                    continue
                try:
                    val = getattr(kmi.properties, prop_name)
                    # Convert non-serializable types
                    if hasattr(val, 'to_list'):
                        val = val.to_list()
                    elif hasattr(val, 'to_dict'):
                        val = val.to_dict()
                    props[prop_name] = val
                except Exception:
                    pass
    except Exception:
        pass
    return props


def _kmi_is_modified(kmi, km_name):
    """Compare user KMI against default to detect modifications."""
    wm = bpy.context.window_manager
    kc_default = wm.keyconfigs.default
    if kc_default is None:
        return True  # Can't compare, assume modified

    for km in kc_default.keymaps:
        if km.name != km_name:
            continue
        for default_kmi in km.keymap_items:
            if default_kmi.idname == kmi.idname:
                if (kmi.type != default_kmi.type or kmi.value != default_kmi.value or
                        kmi.ctrl != default_kmi.ctrl or kmi.shift != default_kmi.shift or
                        kmi.alt != default_kmi.alt or kmi.oskey != default_kmi.oskey or
                        kmi.active != default_kmi.active):
                    return True
                return False
    return True  # Not found in default, consider modified


def _generate_keyconfig_data(scope='MODIFIED'):
    """Generate Blender-compatible keyconfig_data list."""
    wm = bpy.context.window_manager
    kc = wm.keyconfigs.user
    if kc is None:
        return []

    keyconfig_data = []
    for km in kc.keymaps:
        items = []
        for kmi in km.keymap_items:
            if scope == 'MODIFIED' and not _kmi_is_modified(kmi, km.name):
                continue

            kmi_data = {
                "type": kmi.type,
                "value": kmi.value,
                "ctrl": kmi.ctrl,
                "shift": kmi.shift,
                "alt": kmi.alt,
                "oskey": kmi.oskey,
                "key_modifier": kmi.key_modifier,
                "repeat": kmi.repeat,
            }
            props = _kmi_to_properties_dict(kmi)
            items.append((kmi.idname, kmi_data, props))

        if items:
            km_params = {
                "space_type": km.space_type,
                "region_type": km.region_type,
            }
            keyconfig_data.append((km.name, km_params, {"items": items}))

    return keyconfig_data


def _write_export_file(filepath, keyconfig_data):
    """Write a Python script with keyconfig_import_from_data call."""
    abs_path = bpy.path.abspath(filepath)
    dir_path = os.path.dirname(abs_path)
    if dir_path:
        os.makedirs(dir_path, exist_ok=True)

    with open(abs_path, 'w', encoding='utf-8') as f:
        f.write("# Keymap export generated by Keymap Visualizer addon\n")
        f.write("import os\n\n")
        f.write("keyconfig_data = \\\n")
        f.write(repr(keyconfig_data))
        f.write("\n\n")
        f.write('if __name__ == "__main__":\n')
        f.write('    from bl_keymap_utils.io import keyconfig_import_from_data\n')
        f.write('    keyconfig_import_from_data(\n')
        f.write('        os.path.splitext(os.path.basename(__file__))[0],\n')
        f.write('        keyconfig_data)\n')

    return abs_path


def _do_export():
    """Run the export using addon preferences settings. Returns (success, message)."""
    try:
        prefs = bpy.context.preferences.addons["keymap_visualizer"].preferences
        filepath = prefs.export_path
        scope = prefs.export_scope
    except Exception:
        filepath = os.path.join(os.path.dirname(__file__), "exports", "custom_keymap.py")
        scope = 'MODIFIED'

    try:
        data = _generate_keyconfig_data(scope)
        if not data:
            return (False, "No keybindings to export")
        abs_path = _write_export_file(filepath, data)
        return (True, f"Exported to {abs_path}")
    except Exception as e:
        return (False, f"Export failed: {e}")
