"""
Keymap Visualizer – Export functions
"""

import logging
import ast
import bpy
import os
from . import state

_log = logging.getLogger("keymap_visualizer.export")


def _kmi_to_properties_dict(kmi):
    """Extract serializable operator properties from a KMI."""
    props = {}
    try:
        if kmi.properties is not None:
            for prop_name in kmi.properties.bl_rna.properties.keys():
                if prop_name == 'rna_type':
                    continue
                try:
                    val = getattr(kmi.properties, prop_name)
                    # Convert non-serializable types
                    if hasattr(val, 'to_list'):
                        val = val.to_list()
                    elif hasattr(val, 'to_dict'):
                        val = val.to_dict()
                    props[prop_name] = val
                except Exception:
                    _log.debug("Could not serialize property %s", prop_name, exc_info=True)
    except Exception:
        _log.debug("Could not read KMI properties", exc_info=True)
    return props


def _kmi_is_modified(kmi, km_name):
    """Compare user KMI against default to detect modifications."""
    wm = bpy.context.window_manager
    kc_default = wm.keyconfigs.default
    if kc_default is None:
        return True  # Can't compare, assume modified

    for km in kc_default.keymaps:
        if km.name != km_name:
            continue
        for default_kmi in km.keymap_items:
            if default_kmi.idname == kmi.idname:
                if (kmi.type != default_kmi.type or kmi.value != default_kmi.value or
                        kmi.ctrl != default_kmi.ctrl or kmi.shift != default_kmi.shift or
                        kmi.alt != default_kmi.alt or kmi.oskey != default_kmi.oskey or
                        kmi.active != default_kmi.active):
                    return True
                return False
    return True  # Not found in default, consider modified


def _generate_keyconfig_data(scope='MODIFIED'):
    """Generate Blender-compatible keyconfig_data list."""
    wm = bpy.context.window_manager
    kc = wm.keyconfigs.user
    if kc is None:
        return []

    keyconfig_data = []
    for km in kc.keymaps:
        items = []
        for kmi in km.keymap_items:
            if scope == 'MODIFIED' and not _kmi_is_modified(kmi, km.name):
                continue

            kmi_data = {
                "type": kmi.type,
                "value": kmi.value,
                "ctrl": kmi.ctrl,
                "shift": kmi.shift,
                "alt": kmi.alt,
                "oskey": kmi.oskey,
                "key_modifier": kmi.key_modifier,
                "repeat": kmi.repeat,
            }
            props = _kmi_to_properties_dict(kmi)
            items.append((kmi.idname, kmi_data, props))

        if items:
            km_params = {
                "space_type": km.space_type,
                "region_type": km.region_type,
            }
            keyconfig_data.append((km.name, km_params, {"items": items}))

    return keyconfig_data


def _write_export_file(filepath, keyconfig_data):
    """Write a Python script with keyconfig_import_from_data call."""
    abs_path = bpy.path.abspath(filepath)
    dir_path = os.path.dirname(abs_path)
    if dir_path:
        os.makedirs(dir_path, exist_ok=True)

    with open(abs_path, 'w', encoding='utf-8') as f:
        f.write("# Keymap export generated by Keymap Visualizer addon\n")
        f.write("import os\n\n")
        f.write("keyconfig_data = \\\n")
        f.write(repr(keyconfig_data))
        f.write("\n\n")
        f.write('if __name__ == "__main__":\n')
        f.write('    from bl_keymap_utils.io import keyconfig_import_from_data\n')
        f.write('    keyconfig_import_from_data(\n')
        f.write('        os.path.splitext(os.path.basename(__file__))[0],\n')
        f.write('        keyconfig_data)\n')

    return abs_path


def _do_export():
    """Run the export using addon preferences settings. Returns (success, message)."""
    try:
        prefs = state._get_prefs()
        filepath = prefs.export_path
        scope = prefs.export_scope
    except Exception:
        _log.debug("Could not read export preferences, using defaults", exc_info=True)
        filepath = ""
        scope = 'MODIFIED'

    if not filepath:
        filepath = os.path.join(
            bpy.utils.user_resource('CONFIG'), "keymap_exports", "custom_keymap.py"
        )

    try:
        data = _generate_keyconfig_data(scope)
        if not data:
            return (False, "No keybindings to export")
        abs_path = _write_export_file(filepath, data)
        return (True, f"Exported to {abs_path}")
    except Exception as e:
        _log.warning("Export failed", exc_info=True)
        return (False, f"Export failed: {e}")


def _do_import():
    """Import a keyconfig Python file exported by this addon. Returns (success, message)."""
    try:
        prefs = state._get_prefs()
        filepath = prefs.import_path
    except Exception:
        _log.debug("Could not read import preferences", exc_info=True)
        return (False, "Import path not set in addon preferences")

    if not filepath:
        return (False, "Import path is empty")

    abs_path = bpy.path.abspath(filepath)
    if not os.path.isfile(abs_path):
        return (False, f"File not found: {abs_path}")

    try:
        with open(abs_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        _log.warning("Could not read import file", exc_info=True)
        return (False, f"Could not read file: {e}")

    # Parse keyconfig_data from the file
    keyconfig_data = None
    try:
        # Find the line starting with 'keyconfig_data'
        for line_no, line in enumerate(content.splitlines()):
            stripped = line.strip()
            if stripped.startswith("keyconfig_data"):
                # Extract everything after the first '=' on this line and onwards
                eq_pos = content.index("keyconfig_data")
                remainder = content[eq_pos:]
                # Find the '=' sign
                eq_idx = remainder.index('=')
                value_str = remainder[eq_idx + 1:].strip()
                # Remove line-continuation backslash if present
                if value_str.startswith('\\'):
                    value_str = value_str[1:].strip()
                keyconfig_data = ast.literal_eval(value_str)
                break
    except (ValueError, SyntaxError) as e:
        _log.warning("Failed to parse keyconfig_data from file", exc_info=True)
        return (False, f"Failed to parse keyconfig_data: {e}")

    if keyconfig_data is None:
        return (False, "No keyconfig_data found in file")

    if not isinstance(keyconfig_data, list) or not keyconfig_data:
        return (False, "keyconfig_data is empty or invalid")

    # Push undo before applying
    from .keymap_data import _push_undo
    _push_undo()

    # Apply using shared logic from presets
    from .presets import _apply_keyconfig_data
    success, result = _apply_keyconfig_data(keyconfig_data)
    if not success:
        return (False, result)

    return (True, f"Imported {result} bindings from {os.path.basename(abs_path)}")
